name: Build artifact and create release bundle

permissions:
  id-token: write
  packages: write
  contents: read
  attestations: write

on:
  workflow_call:
    secrets:
      GPG_SECRET_KEY:
        required: true
      GPG_PUBLIC_KEY:
        required: true
      GPG_PASS:
        required: true

jobs:
  extract-version:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 2
      - name: Extract Version
        id: extract
        uses: ./.github/actions/get-version
    outputs:
      version: ${{ steps.extract.outputs.release-version }}
      is-snapshot: ${{ steps.extract.outputs.is-snapshot }}

  build-sign-deploy:
    needs: extract-version
    uses: aerospike/shared-workflows/.github/workflows/reusable_artifacts-cicd.yaml@1004088a1b5122b9b71a39b40f619f6b50e78d16
    with:
      gh-artifact-directory: build
      gh-workflows-ref: 1004088a1b5122b9b71a39b40f619f6b50e78d16
      jf-build-name: java-object-mapper
      jf-project: ${{ vars.JFROG_PROJECT }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      version: ${{ needs.extract-version.outputs.version }}
      jar-group-id: com.aerospike
      setup-java: true
      java-version: 17
      java-distribution: "temurin"
      gh-source-path: java-object-mapper
      gh-retention-days: 1
      runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
      build-script: |
        # Maven build
        if [ "${{ needs.extract-version.outputs.is-snapshot }}" == "true" ]; then
          pom_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn versions:set -DnewVersion="${pom_version}-SNAPSHOT" -DgenerateBackupPoms=false -DprocessAllModules
        fi
        
        mvn clean install -B -U -Dgpg.skip=true -DskipTests

        pwd

        LOCAL_REPO=$(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
        GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
        ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

        GROUP_PATH=$(echo "$GROUP_ID" | tr '.' '/')
        ARTIFACT_PATH="$LOCAL_REPO/$GROUP_PATH/$ARTIFACT_ID/$VERSION"

        echo "ARTIFACT_PATH: $ARTIFACT_PATH"
        echo "Copying artifacts to ./build/"
        
        for file in "$ARTIFACT_PATH"/*; do
          if [[ "$file" == *"-jar-with-dependencies.jar" ]] || [[ "$file" == *"_remote.repositories" ]]; then
            continue
          fi
          cp "$file" build/
        done
        
        PARENT_ARTIFACT_ID=java-object-mapper
        PARENT_PATH="$LOCAL_REPO/$GROUP_PATH/$PARENT_ARTIFACT_ID/$VERSION"

        echo "Parent artifact path: $PARENT_PATH"

        if [ -d "$PARENT_PATH" ]; then
          echo "Copying parent POM..."
          cp "$PARENT_PATH"/*.pom build/
          cp "$PARENT_PATH"/*.asc build/ 2>/dev/null || true
        else
          echo "WARNING: Parent POM not found in $PARENT_PATH"
        fi
        
        ls -lar build/
    secrets:
      gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg-key-pass: ${{ secrets.GPG_PASS }}

  create-release-bundle:
    needs: [ extract-version, build-sign-deploy ]
    uses: aerospike/shared-workflows/.github/workflows/reusable_create-release-bundle.yaml@1004088a1b5122b9b71a39b40f619f6b50e78d16
    with:
      jf-project: ${{ vars.JFROG_PROJECT }}
      jf-build-names: ${{ needs.build-sign-deploy.outputs.jf-build-name }}:${{ needs.build-sign-deploy.outputs.jf-build-id }}
      jf-bundle-name: java-object-mapper
      gh-workflows-ref: 1004088a1b5122b9b71a39b40f619f6b50e78d16
      version: ${{ needs.extract-version.outputs.version }}
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}
      dry-run: false

  promote-to-dev:
    needs: [ extract-version, create-release-bundle ]
    name: Promote to DEV
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Setup JFrog CLI
        uses: step-security/setup-jfrog-cli@893a92f96c7727242adf0e603c77b1f2a22390e1 # v4.9.1
        env:
          JF_URL: ${{ vars.JFROG_PLATFORM_URL }}
          JF_PROJECT: ${{ vars.JFROG_PROJECT }}
        with:
          oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ vars.OIDC_AUDIENCE }}

      - name: Check if snapshot build
        run: |
          if [[ "${{ needs.extract-version.outputs.is-snapshot }}" == "true" ]]; then
            echo "Error: this is a SNAPSHOT build. Snapshots are not promoted."
            exit 1
          fi

      - name: Promoting release bundle to DEV
        uses: aerospike/shared-workflows/.github/actions/promote-release-bundle@8ec712eafbec26c8db8d1183688a5fd806560a95 # v3.5.0
        with:
          bundle-name: java-object-mapper
          version: ${{ needs.extract-version.outputs.version }}
          environment: DEV
          jf-project: ${{ vars.JFROG_PROJECT }}
